
    var data = [
      {
        title: "DETAN + GLOW GREEN TEA CLAY MASK",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-2_3_7231ae56-0a07-472c-92c1-7d34bc93cf57_1800x1800.jpg?v=1648088737",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/detanclay_1800x1800.jpg?v=1648088737",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/image-3_1800x1800.png?v=1648088737",
        ],
        size: ["85g"],
        description: [
          "This skin polishing, sun tan removal clay mask promotes a naturally radiant glow",
          "Sandalwood and lemon verbena effectively remove stubborn tan",
          "A de-tan face pack that gives you visibly brighter skin after the very first application",
          "Also infused with kaolin and green tea for a refreshing experience",
          "A bright yellow clay, thick, fresh smelling clay mask for glowing skin",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "1440.43",
        discount: 23,
        rating: "4.8",
        id: "DK0133",
      },
      {
        title: "Age Defense Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/nightcream_2_2e3e7434-5b2f-4cf6-aef9-ade90482eea2_1800x1800.png?v=1658906872",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/age2_1_large.jpg?v=1647261960",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Retinol-Night-Cream_1800x1800.jpg?v=1658906872"
        ],
        size: ["Complete Kit"],
        description: [
          "Get matte, glowing and youthful skin with this Time Reverse Skincare Regimen.",
          "Ideal for normal to matured skin, this combo consists of our bestselling skincare products.",
          "The watermelon cleanser deeply cleanses to remove dirt and excess oil for clean, matte, hydrated and bright skin.",
          "The serum with 100% natural vitamin C from Kakadu Plum repairs damaged skin, reduces dullness and neutralizes free radicals for healthy, glowing skin.",
          "The retinol night cream works overnight to reduce fine lines and wrinkles by boosting collagen production for firm, lifted and youthful skin",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "1188.99",
        discount: 20,
        rating: "4.8",
        id: "DK0153",
      },
      {
        title: "GLOW REVEALING VITAMIN C SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/20VITC_2_1800x1800.png?v=1658907052",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-20_-VIT-C-SERUM_1800x1800.jpg?v=1658907052",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-20_-VIT-C-SERUM_1800x1800.jpg?v=1658907052",
        ],
        size: ["30ml", "Fragrance Free 30 ml"],
        description: [
          "Flaunt healthy, glowing skin with Dot & Key Glow Reviving Vitamin C Serum.",
          "Infused with 100% natural vitamin C from Kakadu Plum, Acerola Cherry and Hyaluronic acid.",
          "Repairs skin damage, minimizes dark spots and signs of ageing. ",
          "Also neutralizes free radicals and boosts collagen production for smooth, soft skin.",
          "Reduces dullness and signs of skin damage with uneven skin tone. ",
          "With regular application, skin appears even-toned, radiant and glowing. ",
          "Water-based, lightweight texture ideal for all skin types, even sensitive skin.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1144.69",
        discount: 15,
        rating: "4.5",
        id: "DK0106",
      },
      {
        title: "VITAMIN C GLOW PINK CLAY MASK",
        images: [
          
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/pinkclaymask_1f29e041-04b7-4b13-875e-0ffa582f92e2_1800x1800.jpg?v=1656935595",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Pink-Clay-Mask_1800x1800.jpg?v=1656935595",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Pink-Clay-Mask_1800x1800.jpg?v=1656935595",
        ],
        size: ["85g"],
        description: [
          "Layer your skin with the power of pink to treat dullness and clear deep-rooted impurities for glowing, nourished and hydrated skin.",
          "Featuring a rich, creamy texture with French pink clay and natural vitamin C from Kakadu Plum, it reverses dull, tired skin to reveal a bright, glowing complexion.",
          "Acerola cherry, the little powerhouse of antioxidants, boosts collagen production to repair skin damage and uneven skin tone.",
          "Additionally, when kaolin and bentonite clay blends with hyaluronic acid, it removes deep-seated impurities while locking in moisture for clean, soft and bouncy skin.",
          "Whether you are getting ready for a party or want to give your skin a 'quick pick-up', this soft pink clay mask is the ideal solution for nourished, hydrated and radiant skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "1479.73",
        discount: 10,
        rating: "3.9",
        id: "DK0132",
      },
      {
        title: "NIGHT RESET RETINOL CREAM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/nightwe_1800x1800.png?v=1648088661",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Age-defence-packaging-box-1_1800x1800.jpg?v=1648088661",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/timereversesleepmask_1800x1800.jpg?v=1648088661"
        ],
        size: ["60ml", "25ml"],
        description: [
          "Wake up to fresh, smooth and youthful glowing skin with this targeted overnight skin treatment",
          "Its luxurious creamy texture is formulated using an age-defense formula with the goodness of retinol, ceramide and hibiscus.",
          "While retinol minimizes wrinkles & fine lines by stimulating collagen formation, hibiscus promotes cell turnover to delay skin’s ageing.",
          "Ceramides protects against environmental damage & locks in moisture to prevent dryness & irritation.",
          "With regular use, skin appears firm, lifted and rejuvenated with a soft, smooth complexion.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "621.13",
        discount: 0,
        rating: "3.9",
        id: "DK0121",
      },
      {
        title: "VITAMIN C GLOW CAPSULE SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/20VITC_2_1800x1800.png?v=1658907052",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-20_-VIT-C-SERUM_1800x1800.jpg?v=1658907052",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-20_-VIT-C-SERUM_1800x1800.jpg?v=1658907052",
        ],
        size: ["30ml"],
        description: [
          "10x more potent Vs existing serum, with 15% Vitamin C + 0.5% Ferulic acid",
          "Hydrates the skin overnight, giving it a dewy glow in the morning",
          "Gel-creme capsule formula with Vitamin E capsules",
          "Brightens & illuminates dull, tired looking skin",
          "Fades dark spots, uneven skin tone & stubborn scars",
          "With time-release technology, it boosts collagen production & skin elasticity",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. Only For Today",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1215.78",
        discount: 23,
        rating: "3.6",
        id: "DK0115",
      },
      {
        title: "Peace Out Acne Duo",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_27_1_1800x1800.png?v=1661255883",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2_11_1800x1800.jpg?v=1661255883",
        ],
        size: ["25ml"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
        ],
        category: "Acne",
        price: "1318.02",
        discount: 30,
        rating: "3.8",
        id: "DK0140",
      },
     

      {
        title: "Glow Elixir Radiance Enhancing Face Oil",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1_2_1800x1800.jpg?v=1644862670",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_2_1800x1800.jpg?v=1644862670",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3_2_1800x1800.jpg?v=1644862670"
        ],
        size: ["20ml"],
        description: [
          "Reveal healthy and glowing skin in every drop with Glow Elixir Radiance Enhancing Face Oil.",
          "100% natural botanical oil featuring vegan formula with zero added fragrance, it is a luxurious skin treat for normal to dry skin.",
          "Infused with antioxidant-rich Rosehip Oil, it fades pigmentation and evens out skin tone to reveal beautiful, radiant skin.",
          "With the goodness of Cloudberry Oil (a rich source of vitamin C), it treats dullness and protects skin from early signs of ageing for healthy, bright skin.",
          "Additionally, Sea Buckthorn (rich in omega-3 and 6 fatty acids) promotes collagen synthesis, boosts elasticity and sloughs away dull dead cells for smooth, supple and moisturized skin.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1318.14",
        discount: 0,
        rating: "4.3",
        id: "DK0107",
      },
      {
        title: "DEEP PORE FOAMING CLEANSER",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Deep-pore-Listing-image2_1_1800x1800.jpg?v=1655309802",
        
        ],
        size: ["120ml"],
        description: [
          "Formulated with potent skin actives, this daily cleanser will provide deep pore care and a brightening effect.",
          "Dense foam will provide brilliant cleansing action to eliminate skin impurities and minimise the appearance of pores.",
          "Additionally, seaweed extract will control excess oil production, keeping skin hydrated, calm and nourished.",
          "Lotus Flower extract will promote cell turnover and fade dark spots for an even-toned complexion.",
          "Sulphate free cleansing molecules will gently remove makeup and sunscreen to unclog pores, leaving skin with a healthy texture.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Face Wash",
        price: "962.76",
        discount: 10,
        rating: "3.9",
        id: "DK0118",
      },
      {
        title: "Spot Clearing Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-9_1_1800x1800.jpg?v=1655310238",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2_3b2fc99c-c2e5-40cd-a011-6906388a18e8_1800x1800.jpg?v=1655310238",
        ],
        size: ["120ml", "25ml", "15ml"],
        description: [
          "Flaunt healthy, even-toned and glowing skin with our Skin Clearing Regime.",
          "Carefully curated with Dot & Key's bestsellers, this skincare regime is ideal for all skin types.",
          "The sulphate-free cleanser with Malic and Lactic acid brilliantly cleanses the skin to unclog pores for clean, milky bright skin.",
          "The serum with 10% niacinamide, 1% zinc and sunflower seed oil fades dark spots and minimizes pores for clear skin with an improved skin texture.",
          "The vitamin C+E moisturizer with 3 types of vitamin C helps reduce dullness and hyperpigmentation for bright, glowing.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Dark Spots",
        price: "1058.09",
        discount: 20,
        rating: "4.9",
        id: "DK0127",
      },
      {
        title: "Acne Busting Kit - 15ml",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Pollution_Acne_1800x1800.jpg?v=1611576921",
        ],
        size: ["30ml"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
          "Curated with skincare products that help fight acne and other related skin problems, it is the best skincare kit for acne-prone, oily skin.",
          "Deep Pore Cleanser: Infused with lactic acid, malic acid & other soothing natural ingredients, it deeply cleanses & unclogs pores for clear, milky bright skin.",
          "5% AHA Toner: An exfoliating toner made with natural fruit acids derived from grapeseed & more that helps improve the texture of the skin, making it look & feel smoother",
          "CICA Night Gel:The night gel powered by calming cica (Centella Asiatica) heals acne, inflammation and acne scars to provide clear, healthy skin with balanced hydration. ",
        ],
        perks: [
          "Pamper yourself and enjoy moisturized hands and feet with Dot & Key's Hand & Foot Dream Cream Duo. ",
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
        ],
        category: "Acne",
        price: "545.01",
        discount: 40,
        rating: "3.9",
        id: "DK0145",
      },
      {
        title: "Goodbye Acne Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_5_1800x1800.jpg?v=1638785649",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2.3_1800x1800.jpg?v=1638785649",
        ],
        size: ["30ml"],
        description: [
          "Formulated with 10% Niacinamide that brightens and 1% Zinc that rejuvenates",
          "A superlight and non-greasy serum",
          "Fades dark spots and minimises appearance of pores",
          "Reduces redness and improves skin’s texture",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Acne",
        price: "1222.80",
        discount: 23,
        rating: "4.5",
        id: "DK0141",
      },
      {
        title: "Watermelon SuperGlow Matte Moisturizer",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/watermelonmoist_7b89d446-5252-46b4-b414-3977572149fe_1800x1800.jpg?v=1656935635",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Watermelon-Moisturizer_1800x1800.jpg?v=1656935635",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Watermelon-Moisturizer_1800x1800.jpg?v=1656935635",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Watermelon-Moisturizer_1800x1800.jpg?v=1656935635",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Watermelon-Moisturizer_1800x1800.jpg?v=1656935635"
        ],
        size: ["60ml"],
        description: [
          "Get plump, dewy, hydrated and glowing skin with Dot & Key Watermelon Superglow Matte Moisturizer.",
          "A lightweight, oil-free matte moisturizer ideal for oily & combination skin.",
          "Powered with glycolic acid it gently exfoliates to remove dead skin cells & unclog pores.",
          "Infused with vitamins and amino acid-rich watermelon juice and moisture magnet hyaluronic acid, this melony goodness thoroughly hydrates skin without making it look oily.",
          "Featuring a super light, matte texture, this moisturizer glides effortlessly onto your skin to control excess oil, shine and acne breakouts for a refined skin texture.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "502.54",
        discount: 23,
        rating: "4.7",
        id: "DK0122",
      },
      {
        title: "TIME REVERSE RETINOL SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/retinolserum_1800x1800.jpg?v=1656934971",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_8_1800x1800.webp?v=1656934971"
        ],
        size: ["30ml"],
        description: [
          "This supercharged serum promises a three-pronged action : 1. Reducing fine lines, 2. Fading dark spots, 3. Enhancing skin’s elasticity.",
          "The retinol serum contains Tripeptides and Retinol, that slows down skin ageing by capturing free radicals and promoting collagen regeneration.",
          "Infused with a botanical blend of Rosehip, Ylang Ylang & Geranium Oils, and highly moisturizing vitamin E & A",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1247.76",
        discount: 23,
        rating: "4.8",
        id: "DK0110",
      },
      {
        title: "10% NIACINAMIDE SPOT CORRECTOR SERUM",
        images: [
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/NIACINAMIDE_1_1800x1800.png?v=1658907926",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Niacinamide-Serum-Listing_0e894038-8710-4252-8c69-9dee74b89a91_1800x1800.jpg?v=1658907926",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Niacinamide-Serum-Listing_07da0baa-0602-4c2e-bac0-4d047be81c3d_1800x1800.jpg?v=1658907926",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Niacinamide-Serum-Listing_e9f689b0-40ce-4858-87e6-6faa038f1e04_1800x1800.jpg?v=1658907926",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Niacinamide-Serum-Listing_44e7539a-4c29-42fa-934b-197b552ab186_1800x1800.jpg?v=1658907926"
        ],
        size: ["30ml"],
        description: [
          "Formulated with 10% Niacinamide that brightens and 1% Zinc that rejuvenates",
          "A superlight and non-greasy serum",
          "Fades dark spots and minimises appearance of pores",
          "Reduces redness and improves skin’s texture",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Acne",
        price: "1256.79",
        discount: 0,
        rating: "4.8",
        id: "DK0138",
      },
      {
        title: "5 Steps To Acne Free Skin",
        images: [
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_24_1800x1800.png?v=1658903761",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/travel2_1800x1800.jpg?v=1658903761",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/travel3_1800x1800.jpg?v=1658903761"
        ],
        size: ["60ml"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
          "Curated with skincare products that help fight acne and other related skin problems, it is the best skincare kit for acne-prone, oily skin.",
          "Deep Pore Cleanser: Infused with lactic acid, malic acid & other soothing natural ingredients, it deeply cleanses & unclogs pores for clear, milky bright skin.",
          "5% AHA Toner: An exfoliating toner made with natural fruit acids derived from grapeseed & more that helps improve the texture of the skin, making it look & feel smoother",
          "CICA Night Gel:The night gel powered by calming cica (Centella Asiatica) heals acne, inflammation and acne scars to provide clear, healthy skin with balanced hydration. ",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
        ],
        category: "Acne",
        price: "1188.91",
        discount: 30,
        rating: "4.6",
        id: "DK0142",
      },
      {
        title: "AHA + BHA HYDRO PEEL GLOW POTION",
        images: [
          "https://images-static.nykaa.com/media/catalog/product/2/6/268ce328904035423624-new1.jpg",
          "https://images-static.nykaa.com/media/catalog/product/2/6/268ce328904035423624-new4.jpg",
          "https://images-static.nykaa.com/media/catalog/product/2/6/268ce328904035423624-new2.jpg"
        ],
        size: ["30ml"],
        description: [
          "Bring home gentler and safer alternative to expensive clinical skin peeling treatments for supple, fresh and bright skin.",
          "The powerful combination of glycolic acid, lactic acid (AHA) and salicylic acid (BHA) gently peel away dead skin cells to reveal new, younger-looking skin.",
          "Also infused with borage flower extract and other natural derivatives, the serum leaves skin feeling nourished and rested with a healthy, glowing complexion.",
          "A lightweight, water-based exfoliating face serum that causes zero skin irritation, thus making it the best option for the ones new to skin peeling treatment.",
          "Free of nasties and dermatologically tested, use this serum twice a week for visibly smooth, soft and clear skin.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. Only For Today",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "837.81",
        discount: 15,
        rating: "4.3",
        id: "DK0116",
      },
      {
        title: "HAND CREAM + SANITIZER, LAVENDER",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/HandCream-L_1800x1800.jpg?v=1638974908",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Other-product-packaging-box-3HandCream_1800x1800.jpg?v=1638974908",
        ],
        size: ["50ml"],
        description: [
          "A perfect hand cream with dual benefits of sanitizer plus moisturizer.",
          "Contains anti-bacterials that get rid of 99.9% germs, as well as moisturizing jojoba and shea actives that offer intense hydration",
          "Its alcohol-free formula also prevents hands from getting dry",
          "Citrusy fragrance of lavender and peppermint will make your hands smell great and feel soft",
          "No nasty chemicals, gentle on skin and free of side-effects",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "680.98",
        discount: 23,
        rating: "3.6",
        id: "DK0124",
      },
      {
        title: "Mask Must Haves",
        images: [
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRDCidPXAKTH4hpGtanc-PgvIAVXNO0gmN3O1tKngmLzKN1fGC57C5j92o9j6nFQOqzAmtzESEy6rTVmV914scD1eRX0x-tREpXuh3LGnljnZG9bQ6jjEDnbA&usqp=CAE",
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTcz-JYclkU22s-vUgEsHJvC2wwXtqmPhSlOACBy0nnAOeTaP0_R6QoWmMsOkMLBE9wRb7EdLxM0vOSu97bvbxwUacJlkLdyrjNy3E_K-b1U1UEysohzRcp&usqp=CAE",
        ],
        size: ["60ml"],
        description: [
          "Formulated with 10% Niacinamide that brightens and 1% Zinc that rejuvenates",
          "A superlight and non-greasy serum",
          "Fades dark spots and minimises appearance of pores",
          "Reduces redness and improves skin’s texture",
          "The Vitamin C Sleep Mask works overnight to repair skin damage and dullness while promoting cell turnover for visibly glowing, radiant and even-toned skin.",
          "It is an ideal skincare kit that also saves your skin from winter dryness and dullness",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Acne",
        price: "1179.02",
        discount: 10,
        rating: "4.0",
        id: "DK0143",
      },
      {
        title: "ILLUMINATING GLOW FACIAL SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/IlluminatingGlowSerum_360x.jpg?v=1610018289",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/sunscreen-packaging-box-4_360x.jpg?v=1596018073",
        ],
        size: ["50ml"],
        description: [
          "Perfect for normal to dry skin, this ultra-light moisturizer-in-serum hydrates & makes your face glow",
          "Contains skin conditioning actives that lock in moisture for hours, revealing soft glowing skin",
          "SPF 15 for daily protection from environmental stresses, reducing signs of dullness and gives you glowing skin",
          "A glow serum delicately scented with the sweet tropical fragrance of frangipani and ylang ylang",
          "No nasty chemicals, 100% gentle on skin and free of side-effects",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "625.12",
        discount: 0,
        rating: "4.1",
        id: "DK0156",
      },
      {
        title: "Best of Vitamin C Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2-4_540x.jpg?v=1637220734",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2-2_360x.jpg?v=1637220734",
        ],
        size: ["Complete Kit"],
        description: [
          "Get clean, matte & glowing skin with our Go for the Glow Skincare Regime.",
          "An ideal skincare regime for dull skin, it contains Dot & Key's bestselling products.",
          "The sulphate-free watermelon cleanser features a juicy gel-like texture that deeply cleanses to remove dirt and oil for clean, matte skin.",
          "The serum with 100% natural vitamin C from Kakadu Plum heals damaged skin and neutralizes free radicals for healthy, glowing skin.",
          "The vitamin C+E moisturizer with 3 types of vitamin C evens skin tone and reduces dark spots for intensely hydrated, bright skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "516.20",
        discount: 40,
        rating: "4.4",
        id: "DK0154",
      },
      {
        title: "Best of Vitamin C Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2-4_1800x1800.jpg?v=1637220734",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2-2_1800x1800.jpg?v=1637220734",
        ],
        size: [],
        description: [
          "Get clean, matte & glowing skin with our Go for the Glow Skincare Regime.",
          "An ideal skincare regime for dull skin, it contains Dot & Key's bestselling products.",
          "The sulphate-free watermelon cleanser features a juicy gel-like texture that deeply cleanses to remove dirt and oil for clean, matte skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Dark Spots",
        price: "1397.18",
        discount: 0,
        rating: "3.9",
        id: "DK0128",
      },
      {
        title: "ALPHA ARBUTIN RADIANCE SERUM",
        images: [
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/alpha_d391f76e-ef30-427f-8657-3cfe4c8d84eb_1800x1800.jpg?v=1656934978",
         "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_10_1800x1800.webp?v=1656934978"
        ],
        size: ["30ml"],
        description: [
          "India's first dual-phase serum with distinct oil+water parts for a clear, even-toned, radiant complexion.",
          "The oil part is infused with rosehip oil to combat hyperpigmentation.",
          "The water part combines alpha arbutin and azelaic acid to inhibit melanin production.",
          "Safe for all skin types, it will also fight blemishes & discolouration.",
          "Mix it well before application & enjoy visibly nourished, even-toned skin.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "701.06",
        discount: 40,
        rating: "4.8",
        id: "DK0109",
      },
      {
        title: "Watermelon SuperGlow Facial Gel Cleanser",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Watermelon-Cleanser-Listing_1800x1800.jpg?v=1656934311",
          "https://m.media-amazon.com/images/I/715H9tg7zxL._SL1500_.jpg",
          "https://m.media-amazon.com/images/I/41F-bAzJ2gL._SL1500_.jpg",
          "https://m.media-amazon.com/images/I/61wOcnQvAgL._SL1500_.jpg",
        ],
        size: ["120ml"],
        description: [
          "Treat your skin with a juicy burst of hydration in every wash with Watermelon SuperGlow Facial Gel Cleanser.",
          "A sulphate-free, juicy skin treat, the cleanser features a gel-like texture that's ideal for all skin types.",
          "Infused with the goodness of watermelon extract, it deeply cleanses and unclogs pores of oil and dirt while boosting the cell renewal process for clean, matte and bright skin.",
          "Powered by Sodium Ascorbyl Phosphate(Vitamin C), it protects skin from damaging free radicals and checks acne breakout to reveal healthy, glowing skin.",
          "The additional infusion of soothing cucumber reduces redness and calms inflammation to provide hydrated, plump skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "582.37",
        discount: 40,
        rating: "4.5",
        id: "DK0155",
      },
      {
        title: "VITAMIN C GLOW CAPSULE SERUM",
        images: [
          "https://rukminim1.flixcart.com/image/416/416/kvsfhjk0/fairness/g/w/q/30-glow-booster-capsule-serum-15-vitamin-c-0-5-ferulic-skin-original-imag8myc7vvbbm2h.jpeg?q=70"
        ],
        size: ["30ml"],
        description: [
          "10x more potent Vs existing serum, with 15% Vitamin C + 0.5% Ferulic acid",
          "Hydrates the skin overnight, giving it a dewy glow in the morning",
          "Gel-creme capsule formula with Vitamin E capsules",
          "Brightens & illuminates dull, tired looking skin",
          "Fades dark spots, uneven skin tone & stubborn scars",
          "With time-release technology, it boosts collagen production & skin elasticity",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "1350.01",
        discount: 10,
        rating: "4.7",
        id: "DK0152",
      },
      {
        title: "SKIN AWAKENING MOISTURIZING SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/SkinAwakening_360x.jpg?v=1610017602",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Mint-packaging-box-2SkinAwakeningSerum_360x.jpg?v=1610017602",
        ],
        size: ["50ml", "Fragrance Free 50 ml"],
        description: [
          "This vitamin-boost moisturizing serum energizes your skin every morning, while gently soothing sensitive or irritated areas",
          "Acts as a face moisturizer that rejuvenates the skin with icy peppermint oil and soothing lavender oil",
          "A face serum formulated with high-quality spent grain wax, cold-pressed argan oil and shea butter ",
          "No nasty chemicals like parabens, alcohol and phthalates - gentle on skin and free of side-effects",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. Only For Today",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "716.69",
        discount: 30,
        rating: "3.7",
        id: "DK0112",
      },
      {
        title: "Age Defense Skincare Regime",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_0b03915d-fd45-4f70-b766-e80d87e99975_1800x1800.jpg?v=1639046585",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2a_1800x1800.jpg?v=1639046585",
        ],
        size: ["120ml", "25ml", "15ml"],
        description: [
          "Get matte, glowing and youthful skin with this Time Reverse Skincare Regimen. ",
          "Ideal for normal to matured skin, this combo consists of our bestselling skincare products.",
          "The watermelon cleanser deeply cleanses to remove dirt and excess oil for clean, matte, hydrated and bright skin.",
          "The serum with 100% natural vitamin C from Kakadu Plum repairs damaged skin, reduces dullness and neutralizes free radicals for healthy, glowing skin.",
          "The retinol night cream works overnight to reduce fine lines and wrinkles by boosting collagen production for firm, lifted and youthful skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Dark Spots",
        price: "586.73",
        discount: 0,
        rating: "4.9",
        id: "DK0129",
      },
      {
        title: "WATERMELON SUPERGLOW FACIAL GEL CLEANSER",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/WATERMELONWASH_1_1800x1800.jpg?v=1656934311",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Watermelon-Cleanser-Listing_1800x1800.jpg?v=1656934311",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Watermelon-Cleanser-Listing_1800x1800.jpg?v=1656934311",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Watermelon-Cleanser-Listing_1800x1800.jpg?v=1656934311",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Watermelon-Cleanser-Listing_1800x1800.jpg?v=1656934311",
        ],
        size: ["120ml"],
        description: [
          "Treat your skin with a juicy burst of hydration in every wash with Watermelon SuperGlow Facial Gel Cleanser.",
          "A sulphate-free, juicy skin treat, the cleanser features a gel-like texture that's ideal for all skin types.",
          "Infused with the goodness of watermelon extract, it deeply cleanses and unclogs pores of oil and dirt while boosting the cell renewal process for clean, matte and bright skin.",
          "Powered by Sodium Ascorbyl Phosphate(Vitamin C), it protects skin from damaging free radicals and checks acne breakout to reveal healthy, glowing skin.",
          "The additional infusion of soothing cucumber reduces redness and calms inflammation to provide hydrated, plump skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Face Wash",
        price: "758.56",
        discount: 30,
        rating: "4.7",
        id: "DK0117",
      },
      {
        title: "CHOCOLATE GLOW MOUSSE FACE MASK",
        images: [
         
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/image-4_1800x1800.png?v=1638990062",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/website-1080-X-1080_1800x1800.jpg?v=1638990062",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/chocolatemasktexture_1800x1800.jpg?v=1638990062",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/product-usp-2_1800x1800.jpg?v=1638990062",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/chocolate_Mask_1800x1800_4015046f-2199-4fad-9cd8-80dabe004d0d_1800x1800.jpg?v=1638990062",
        ],
        size: ["60ml"],
        description: [
          "Formulated with home-grown artisanal raw cocoa powder by ALL THINGS CHOCOLATE and zesty peppermint oil.",
          "Chocolate Mousse-like texture that helps reveal a natural glow by clearing clogged pores.",
          "Rejuvenates dull, tired skin and helps fade stubborn tan.",
          "Hydrates and nourishes the skin while minimizing the visible signs of UV damage -Peppermint oil leaves a cooling and calming effect on the skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "890.50",
        discount: 30,
        rating: "4.6",
        id: "DK0137",
      },
      {
        title: "VITAMIN C + E SUPER BRIGHT MOISTURIZER",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/LIPMASKW_APPLI_1_1800x1800.png?v=1658907666",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Lip-Plumpin-Mask_146fb679-0960-49a5-b438-ae49b60d863a_1800x1800.jpg?v=1658907666",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Lip-Plumpin-Mask_6528a3a5-1f37-4399-a8d8-104a5afb6991_1800x1800.jpg?v=1658907666",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Lip-Plumpin-Mask_b23993c9-a240-4c02-ba5f-e769c33a5f0c_1800x1800.jpg?v=1658907666",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Lip-Plumpin-Mask_47c8041c-839b-4d4c-8663-4dcafeda13ae_1800x1800.jpg?v=1658907666",
        ],
        size: ["60ml"],
        description: [
          "Turn your glow on with 3 types of vitamin C backed by vitamin E.",
          "Powered by 100% natural vitamin C from Kakadu Plum, ethyl ascorbic acid & sodium ascorbyl phosphate.",
          "Helps fade dark spots & hyperpigmentation for even-toned, glowing skin.",
          "Intensely moisturizes while improving skin's elasticity for a hydrated, firm texture.",
          "Lightweight, sorbet-like texture ideal for all skin types.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "613.06",
        discount: 23,
        rating: "4.0",
        id: "DK0120",
      },
      {
        title: "CHARCOAL MOUSSE CLAY MASK",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Product-texture-6_1800x1800.jpg?v=1638990039",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/acne-packaging-box-1_1800x1800.jpg?v=1638990039",
        ],
        size: ["85g"],
        description: [
          "Activate your tired, dull and congested skin with the power of activated charcoal for clear, smooth, calm and balanced skin.",
          "Enriched with activated charcoal, detoxify your skin, unclog pores and reduce blackheads for a clean, even-toned and smooth texture.",
          "With the goodness of natural skin healer Eucalyptus, this all skin-friendly clay mask reduces inflammation and skin irritation to deliver a rested complexion.",
          "The additional infusion of antioxidant-rich clary sage oil strengthens sagging skin, tightens the pores and balances oil levels for optimum nourishment.",
          "Featuring a thick, mousse-like texture, treat your skin with this clay mask twice a week for a healthy, smooth, clean and clarified complexion.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "571.38",
        discount: 15,
        rating: "4.5",
        id: "DK0134",
      },
      {
        title: "HAND CREAM + SANITIZER, ROSE",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/HandCream-L_1800x1800.jpg?v=1638974908",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Other-product-packaging-box-3HandCream_1800x1800.jpg?v=1638974908",
        ],
        size: ["50ml"],
        description: [
          "A best hand cream solution with dual benefits of sanitizer plus moisturizer.",
          "Formulated with moisturizing jojoba and shea actives that offer intense hydration",
          "This non-drying, alcohol-free formula gets rid of 99.9% germs while softening the hands",
          "Citrusy fragrance of rose geranium will make your hands smell and feel beautiful for hours",
          "No nasty chemicals, gentle on skin and free of side-effects",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "864.16",
        discount: 0,
        rating: "4.8",
        id: "DK0126",
      },
      {
        title: "CICA CALMING SKIN RENEWING NIGHT GEL",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-5_1_4494a133-19ca-46ad-9ec2-19a60ad70e48_1800x1800.jpg?v=1655310163",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard2_b3fccc55-74bf-40ce-b031-534f73363bab_1800x1800.jpg?v=1655310163",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard3_1482e6b4-24b2-41fd-839e-72963faf531f_1800x1800.jpg?v=1655310163",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard4_936cb3f6-61b1-4295-91f6-83ee9cb454b7_1800x1800.jpg?v=1655310163",
        ],
        size: ["60ml"],
        description: [
          "Get acne-free skin with Dot & Key Cica Calming Skin Renewing Night Gel.",
          "A lightweight, oil-free & non-comedogenic night gel with no added fragrance, it is ideal for acne-prone, oily & sensitive skin.",
          "Powered by cica or Centella Asiatica, it rapidly heals acne and soothes skin inflammation.",
          "Infused with niacinamide, it helps fade acne scars and prevents further acne breakout.",
          "Additionally, the goodness of green tea & hyaluronic acid controls excess oil, calms skin irritation and offers balanced hydration.",
          "When used every day at night, skin appears clear, clarified, renewed and rested with the right amount of hydration.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "568.50",
        discount: 10,
        rating: "4.1",
        id: "DK0119",
      },
      {
        title: "VITAMIN C + E SUPER BRIGHT MOISTURIZER",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_25_1_1800x1800.jpg?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_1_2307c9ca-78aa-4f07-8df1-f7addfbea6b5_1800x1800.png?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Vit-C-Moisturizer-A_-Listing-NEW_3c11ec4f-722d-4694-a8f0-a0b38e9657be_1800x1800.jpg?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Vit-C-Moisturizer-A_-Listing-NEW_926129b3-e96c-485a-b5d7-db7f6df437b2_1800x1800.jpg?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Vit-C-Moisturizer-A_-Listing-NEW_8c98d559-c863-418e-8d3e-56479faa66e7_1800x1800.jpg?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Vit-C-Moisturizer-A_-Listing-NEW_a68179f3-06d5-4df3-9791-53a5ec8344bb_1800x1800.jpg?v=1660731137",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/55f28620586e40cd991b76baca56c458.thumbnail.0000000_360x.jpg?v=1631884597",
        ],
        size: ["60ml"],
        description: [
          "Turn your glow on with 3 types of vitamin C backed by vitamin E.",
          "Powered by 100% natural vitamin C from Kakadu Plum, ethyl ascorbic acid & sodium ascorbyl phosphate.",
          "Helps fade dark spots & hyperpigmentation for even-toned, glowing skin.",
          "Intensely moisturizes while improving skin's elasticity for a hydrated, firm texture.",
          "Lightweight, sorbet-like texture ideal for all skin types.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "1169.75",
        discount: 15,
        rating: "4.5",
        id: "DK0147",
      },
      {
        title: "CICA CALMING SKIN RENEWING NIGHT GEL",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_3_8124891e-d162-491c-b41e-43ea643926f1_1800x1800.png?v=1658906811",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-CICA-NIGHT-GEL_1800x1800.jpg?v=1658906811",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-CICA-NIGHT-GEL_1800x1800.jpg?v=1658906811",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-CICA-NIGHT-GEL_1800x1800.jpg?v=1658906811",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-CICA-NIGHT-GEL_1800x1800.jpg?v=1658906811",
        ],
        size: ["85mg"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
        ],
        category: "Acne",
        price: "1173.01",
        discount: 30,
        rating: "4.1",
        id: "DK0146",
      },
      {
        title: "Mask Must Haves",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-3_16_1a9d9d52-bb4b-44b4-a0f3-e83b0696c320_1800x1800.jpg?v=1658907159",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1_34_1800x1800.jpg?v=1658907159",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-2_22_1800x1800.jpg?v=1658907159",
        ],
        size: ["30ml"],
        description: [
          "Seeking your answer to instantly hydrated, plump and glowing skin? We've got you sorted with the Mask Must-Haves skincare duo.",
          "Who is it ideal for? A skincare kit ideal for dry and dull skin (also great for all skin types), it contains Rose Gel Mask and Vitamin C Sleep Mask.",
          "The Rose Gel Mask is a 15-minute wash-off gel mask with real rose petals, Damask Rose Extract and other ingredients that instantly hydrates and refines skin texture for firm, plump and dewy bright skin.",
          "The Vitamin C Sleep Mask works overnight to repair skin damage and dullness while promoting cell turnover for visibly glowing, radiant and even-toned skin.",
          "It is an ideal skincare kit that also saves your skin from winter dryness and dullness.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "1176.23",
        discount: 30,
        rating: "4.8",
        id: "DK0157",
      },
      {
        title: "FOOT CREAM + DEODORIZER, MINT",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/HandCream-M_1800x1800.jpg?v=1644916543",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Other-product-packaging-box-2HandCream_1800x1800.jpg?v=1644916543",
        ],
        size: ["50ml"],
        description: [
          "A 2-in-1 foot care cream with benefits of a moisturizer plus deodorizer.",
          "Keeps your feet hydrated and odour-free while also nourishing cracked heels",
          "Its anti-perspirant foot cream formulated with camphor and peppermint oil to help fight sweat and odour",
          "It is scented delicately with calming lavender and icy peppermint essential oils for long lasting freshness",
          "No nasty chemicals, gentle on skin and free of side-effects",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "1432.30",
        discount: 0,
        rating: "4.3",
        id: "DK0125",
      },
      {
        title: "Superfood Skin Nourishing Face Oil",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1_1_1800x1800.jpg?v=1638975041",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5_1_1800x1800.jpg?v=1638975041",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/6_1_1800x1800.jpg?v=1638975041",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/7_1800x1800.jpg?v=1638975041",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1_1_1800x1800.jpg?v=1638975041",
        ],
        size: ["20ml"],
        description: [
          "Give your skin its daily dose of superfoods for healthy and nourished skin with Superfood Skin Nourishing Face Oil.",
          "Blending 7 miraculous superfood oils in one, it's a quick-absorbing, non-greasy face oil ideal for very dry skin.",
          "Infused with Avocado Oil rich in omega-6 fatty acids, it boosts collagen synthesis to defy early signs of ageing for plump, youthful skin.",
          "With this comes the goodness of Flaxseed Oil, a rich source of omega-3 fatty acids which intensely hydrates skin and smoothen the texture for supple, plump skin.",
          "Jojoba oil, a rich source of Vitamin E, moisturises the skin without clogging pores and renews skin’s natural balance resulting in a youthful, healthy bounce.",
          "All-natural, vegan face oil with zero added fragrance, get healthy, nourished skin in every drop.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "553.03",
        discount: 0,
        rating: "3.6",
        id: "DK0108",
      },
      {
        title: "UNDERARM DETOX CHARCOAL MASK",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/underarmdetoxcharcoalmask_92ab1477-4bc4-4bff-bfc6-272eabd02709_1800x1800.png?v=1627881120",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/D_K_100ml_Underarm_Detox_bottle_final_CapChanged2_1800x1800.jpg?v=1628233132",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/pigmentation-packaging-box-2_1800x1800.jpg?v=1628233134",
        ],
        size: ["100g"],
        description: [
          "Designed for underarm skin to minimize pigmentation and body odour",
          "An underarm mask formulated with active charcoal, jojoba and tea tree oils",
          "It helps lighten dark underarms, remove dead skin cells, dry sweat and accumulated impurities.",
          "Calcium-vitamin complex helps restore the natural even tone of the skin",
          "The zesty peppermint and tea tree oils acts as a deodorizer, leaving skin feeling fresh for long",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "1087.81",
        discount: 23,
        rating: "4.1",
        id: "DK0136",
      },
      {
        title: "5-in-1 VITAMIN C GLOW KIT",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1_14_1800x1800.jpg?v=1656478968",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_15_1800x1800.jpg?v=1656478968",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3_17_1800x1800.jpg?v=1656478968",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1_14_1800x1800.jpg?v=1656478968",
        ],
        size: ["Complete Kit"],
        description: [
          "Take your glow wherever you go with this 5-in-1 Vitamin C Glow Camp Kit.",
          "Consists of Dot & Key's top 5 skincare products to alleviate dull, dehydrated, damaged and pigmented skin.",
          "Each product is infused with skin-loving ingredients such as natural vitamin C from Kakadu Plum, Ethyl Ascorbic Acid, Sodium Ascorbyl Phosphate, probiotics and more for a revived complexion.",
          "When used together as a regime, get visibly nourished, hydrated, even-toned and glowing skin.",
          "Also works as a great gifting option for both men & women.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "726.29",
        discount: 10,
        rating: "4.3",
        id: "DK0150",
      },
      {
        title: "GLOW REVEALING VITAMIN C SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_4_1800x1800.png?v=1657603288",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Vitamin-C-Serum--Listing_1800x1800.jpg?v=1657603288",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Vitamin-C-Serum--Listing_1800x1800.jpg?v=1657603288",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Vitamin-C-Serum--Listing_1800x1800.jpg?v=1657603288",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Vitamin-C-Serum--Listing_1800x1800.jpg?v=1657603288",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/6-Vitamin-C-Serum--Listing_1800x1800.jpg?v=1657603288",
        ],
        size: ["30ml", "Fragrance Free 30 ml"],
        description: [
          "Flaunt healthy, glowing skin with Dot & Key Glow Reviving Vitamin C Serum.",
          "Infused with 100% natural vitamin C from Kakadu Plum, Acerola Cherry and Hyaluronic acid.",
          "Repairs skin damage, minimizes dark spots and signs of ageing.",
          "Also neutralizes free radicals and boosts collagen production for smooth, soft skin.",
          "Reduces dullness and signs of skin damage with uneven skin tone.",
          "With regular application, skin appears even-toned, radiant and glowing.",
          "Water-based, lightweight texture ideal for all skin types, even sensitive skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "1249.88",
        discount: 0,
        rating: "4.2",
        id: "DK0148",
      },
      {
        title: "Hand & Foot Dream Cream Duo",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/foot_31e6a500-8d9a-4833-9365-e19f6eb36772_1800x1800.jpg?v=1650975640",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/foot1_1800x1800.jpg?v=1650975640",
        ],
        size: ["30ml"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
          "Curated with skincare products that help fight acne and other related skin problems, it is the best skincare kit for acne-prone, oily skin.",
          "Deep Pore Cleanser: Infused with lactic acid, malic acid & other soothing natural ingredients, it deeply cleanses & unclogs pores for clear, milky bright skin.",
          "5% AHA Toner: An exfoliating toner made with natural fruit acids derived from grapeseed & more that helps improve the texture of the skin, making it look & feel smoother",
          "CICA Night Gel:The night gel powered by calming cica (Centella Asiatica) heals acne, inflammation and acne scars to provide clear, healthy skin with balanced hydration. ",
        ],
        perks: [
          "Pamper yourself and enjoy moisturized hands and feet with Dot & Key's Hand & Foot Dream Cream Duo. ",
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
        ],
        category: "Acne",
        price: "1307.05",
        discount: 15,
        rating: "4.1",
        id: "DK0144",
      },
      {
        title: "ILLUMINATING GLOW FACIAL SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/IlluminatingGlowSerum_360x.jpg?v=1610018289",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/sunscreen-packaging-box-4_360x.jpg?v=1596018073",
        ],
        size: ["50ml"],
        description: [
          "Perfect for normal to dry skin, this ultra-light moisturizer-in-serum hydrates & makes your face glow",
          "Contains skin conditioning actives that lock in moisture for hours, revealing soft glowing skin",
          "Infused with antioxidant-rich Rosehip Oil, it fades pigmentation and evens out skin tone to reveal beautiful, radiant skin.SPF 15 for daily protection from environmental stresses, reducing signs of dullness and gives you glowing skin",
          "A glow serum delicately scented with the sweet tropical fragrance of frangipani and ylang ylang",
          "No nasty chemicals, 100% gentle on skin and free of side-effects",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. Only For Today",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1067.47",
        discount: 23,
        rating: "4.1",
        id: "DK0113",
      },
      {
        title: "Acne Aftercare Trio",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/7_6_1800x1800.jpg?v=1658901504",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/7.1_1800x1800.jpg?v=1658901505",
        ],
        size: ["120ml", "85GM", "15ml"],
        description: [
          "Pamper your skin with the ultimate post-acne treatment with the potent Acne Aftercare Trio.",
          "Curated with skincare products that help fight acne and other related skin problems, it is the best skincare kit for acne-prone, oily skin.",
          "The Deep Pore Foaming Cleanser helps unclog and tighten the pores with the power of lactic acid, malic acid and other natural ingredients for clean, milky bright skin.",
          "The Green Clay Mask supercharged with matcha and tamanu oil detoxifies the skin, prevents further acne breakout and controls excess oil for clear, and clarified skin.",
          "The niacinamide serum treats acne scars and reduces pores with 10% Niacinamide, 1% Zinc and sunflower seed oil for even-toned, healthy skin.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Dark Spots",
        price: "661.39",
        discount: 10,
        rating: "4.7",
        id: "DK0130",
      },
      {
        title: "72 HR HYDRATING GEL + PROBIOTICS",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/PROBIOTICS_1_1_1_1_1_e0123849-0a5d-4c37-9ef6-96ad3836c842_1800x1800.jpg?v=1660732568",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Probiotics-Gel_1800x1800.jpg?v=1660732568",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Probiotics-Gel_1800x1800.jpg?v=1660732568",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4-Probiotics-Gel_1800x1800.jpg?v=1660732568",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5-Probiotics-Gel_1800x1800.jpg?v=1660732568",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/6-Probiotics-Gel_1800x1800.jpg?v=1660732568",
        ],
        size: ["60ml", "25ml"],
        description: [
          "Drench your skin in 72 hours of hydration with Dot & Key Hydrating Gel + Probiotics.",
          "Packed with the goodness of Hyaluronic Acid, Japanese Rice Water and Probiotics.",
          "Intensely hydrates for long hours, and maintains skin’s moisture barrier.",
          "Balances skin's microbiome and improves overall skin texture.",
          "Alleviates dull, dehydrated and parched skin lacking nourishment. ",
          "With regular application, skin appears plump, hydrated and dewy. ",
          "Oil-free, lightweight gel - Ideal for every skin type.",
        ],
        perks: [
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Moisturizer",
        price: "737.06",
        discount: 30,
        rating: "4.1",
        id: "DK0123",
      },
      {
        title: "ACNE DEFENSE GREEN CLAY MASK",
        images: [
         
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/1-Green-Clay-Mask_1800x1800.png?v=1658907624",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2-Green-Clay-Mask_1199e218-7da0-4c22-8715-3c12fbcad62c_1800x1800.jpg?v=1658907624",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3-Green-Clay-Mask_88b8a99f-55fa-4585-b100-975c09edff92_1800x1800.jpg?v=1658907624",
        ],
        size: ["85g"],
        description: [
          "An anti acne clay mask that removes toxins to combat recurring acne and skin damage from pollution.",
          "Supercharged with matcha tea and tamanu oil, it detoxifies and mattifies your skin in just 10 minutes.",
          "Eucalyptus and neem oil provide a soothing experience, while French Green Clay draws out deep-dwelling impurities to unclog pores.",
          "Salicylic acid in the face mask minimises the appearance of acne scars, pimples and blemishes.",
          "A perfect non comedogenic clay mask for congested, acne prone skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Clay Masks",
        price: "873.79",
        discount: 10,
        rating: "3.8",
        id: "DK0131",
      },
      {
        title: "PHA + BAKUCHIOL DAILY PEEL RESURFACING MILK SERUM",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Untitled-1_23_1800x1800.png?v=1658823231",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/howtouse_1800x1800.jpg?v=1658823231",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/howtouse_1800x1800.jpg?v=1639053810",
        ],
        size: ["30ml"],
        description: [
          "A unique lightweight leave-on daily serum formulated with PHA & Bakuchiol extracts for gentle & natural exfoliation",
          "Made with PHAs, the new gen of AHAs & BHAs that effectively and gently peel away the dull outer layer of the skin",
          "Bakuchiol, a natural retinol alternative that has a soothing effect, helps reduce the appearance of fine lines & wrinkles while reducing skin discolourations caused by environmental exposure",
          "Natural botanicals extracts like aloe vera leaf juice, chamomile and white tea helps calm irritations while hyaluronic provides healthy hydration",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. *Only For Today*",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "1031.04",
        discount: 40,
        rating: "4.0",
        id: "DK0111",
      },
      {
        title: "GLOW ACCELERATOR 30% AHA + 2% BHA",
        images: [
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/gloes_1800x1800.jpg?v=1656934991",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/GlowAccelerator_1800x1800.jpg?v=1656934991",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/glowacceleratorcleansingsolution_1800x1800.png?v=1656934991",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/gloes_1800x1800.jpg?v=1656934991",
        ],
        size: ["20ml"],
        description: [
          "With 5 acid power : glycolic acid, lactic acid, citric acid, mandelic and salicylic acid.",
          "High Performance Peel 3X advanced exfoliation for glowing skin.",
          "The blend of natural ingredients will soothe and nourish skin post exfoliation.",
          "Hyaluronic acid will hydrate the skin, keeping it soft and supple.",
        ],
        perks: [
          "BUY 1 GET 1 On All Serums.Applicable Once Per order. Only For Today",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Serum and Oil",
        price: "754.99",
        discount: 15,
        rating: "4.7",
        id: "DK0114",
      },
      {
        title: "DAMASK ROSE RESURFACING GEL MASK",
        images: [
          
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/Artboard1-4_1_10b465b9-d11f-4394-9ddd-2eef7ae4037d_1800x1800.jpg?v=1655310309",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/2_7_1800x1800.png?v=1655310309",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/3_9_1800x1800.png?v=1655310309",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/4_9_1800x1800.png?v=1655310309",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/5_7_1800x1800.png?v=1655310309",
          "https://cdn.shopify.com/s/files/1/0361/8553/8692/products/6_4_1800x1800.png?v=1655310309",
        ],
        size: ["25ml"],
        description: [
          "Give your skin a luxe glow treatment to reveal plump, dewy glowing skin with Damask Rose Resurfacing Gel Mask.",
          "A 15-min wash off soft gel mask featuring real rose petals, ideal for dry, dull and dehydrated skin.",
          "Infused with Damask Rose extract (rose oil+rose water+dry rose petals), it boosts collagen synthesis to enhance elasticity and firmness for petal-soft, youthful skin.",
          "With the goodness of chamomile extract and aloe vera, it helps soothe inflammation, reduces redness and retains moisture for nourished skin with a refined texture.",
          "The additional infusion of hyaluronic acid intensely hydrates skin and locks-in moisture for supple & bouncy skin.",
        ],
        perks: [
          "Get Silicone Applicator Free with this product",
          "FREE Hand Foot duo on orders above 899",
          "Pick your FREE 5-in-1 kit above 1899",
          "FREE Face Roller + Face Oil above 2799",
          "Additionally, Free Body Lotion on all orders above 899",
          "Buy 2 Get 2 FREE on Bodycare Range",
          "BUY 3 Get 25% of on Ikwi products",
          "Extra 3% off on all prepaid orders",
          "20% Cashback on all orders",
        ],
        category: "Skin Glow",
        price: "918.19",
        discount: 0,
        rating: "4.3",
        id: "DK0151",
      },
    ];
    


// getTheData()

// async function getTheData(){
//   let res = await fetch(`http://localhost:3000/products`);
//   let data = await res.json();
//   console.log(data)
//   appendData(data);
// }



let appendData=(data)=>{
  let container = document.getElementById("container")
  data.forEach((el)=>{
    let div = document.createElement("div");
    div.onclick=()=>{
      localStorage.setItem("product",JSON.stringify(el))
    }
    let img = document.createElement("img");
    img.src=el.images[0]
    let title = document.createElement("h3");
    title.innerText=el.title;
    let price = document.createElement("p");
    price.innerText="₹"+" "+el.price;
    let btn = document.createElement("button");
    btn.innerText="Add To Cart"
    btn.onclick=()=>{
      addTocart(el)
    }
    div.append(img,title,price,btn);
    container.append(div)
  })
}

appendData(data);